#NOM	: makefile
#CLASSE	: PROCESS - LabosProcess
#OBJET	: Makefile du programme PROCESS062
#HOWTO	: make; make clean
#AUTEUR : Michaël Vandycke, 02/2013

demo:	Process062 Demo
	@clear
	@./Demo

Process062:	Process062.c
	gcc Process062.c -o Process062

clean:
	rm -f Process062 .aliasrc *~
