#NOM	: makefile
#CLASSE	: FS - LabosFS
#OBJET	: Makefile du programme FS061
#HOWTO	: make; make clean
#AUTEUR : Michaël Vandycke, 02/2013

demo:	FS061 Demo
	@clear
	@./Demo

FS061:	FS061.c
	gcc FS061.c -o FS061

clean:
	rm -f FS061 *~
